{{- if (index .Values "selfsigned-bundle").enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.namespace.name }}-selfsigned-issuer
  namespace: {{ (index .Values "cert-manager").namespace }}
  labels:
    {{- include "squid.labels" . | nindent 4 }}
spec:
  selfSigned: {}
{{- end }} 
