apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "squid.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "squid.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "squid.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "squid.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "squid.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      
      # --- INIT CONTAINER ---
      # This container runs as root to prepare certificates, initialize the SSL DB,
      # and set the correct file permissions before the main Squid container starts.
      initContainers:
      - name: squid-init
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          # Must run as root to perform chown
          runAsUser: 0
        command:
          - /bin/sh
          - -c
          - |
            set -e
            echo "Initializing SSL certificate database at /var/spool/squid/ssl_db..."
            # 1. Create the database structure.
            /usr/lib64/squid/security_file_certgen -c -s /var/spool/squid/ssl_db -M 16MB

            echo "Setting permissions on /var/spool/squid for user {{ .Values.securityContext.runAsUser }}..."
            # 2. Change ownership to the non-root user of the main container.
            chown -R {{ .Values.securityContext.runAsUser }}:{{ .Values.securityContext.runAsGroup }} /var/spool/squid
            
            echo "Initialization complete."
 
        volumeMounts:
        # Mount the shared volume.
        - name: squid-spool-vol
          mountPath: /var/spool/squid    

      containers:
        - name: squid
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3128
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            tcpSocket:
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: squid-config
              mountPath: /etc/squid/squid.conf
              subPath: squid.conf
            # Mount the shared volume for the certificates
            - name: squid-certs-secret
              mountPath: /etc/squid/certs
              readOnly: true
            # Mount the entire spool directory for the main container
            - name: squid-spool-vol
              mountPath: /var/spool/squid              
        {{- if .Values.squidExporter.enabled }}
        - name: squid-exporter
          image: "{{ .Values.squidExporter.image.repository }}:{{ .Values.squidExporter.image.tag }}"
          imagePullPolicy: {{ .Values.squidExporter.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: {{ .Values.squidExporter.port }}
              protocol: TCP
          env:
            - name: SQUID_HOSTNAME
              value: "localhost"
            - name: SQUID_PORT
              value: "{{ .Values.service.port }}"
            - name: SQUID_EXPORTER_LISTEN
              value: ":{{ .Values.squidExporter.port }}"
            - name: SQUID_EXPORTER_METRICS_PATH
              value: "{{ .Values.squidExporter.metricsPath }}"
            - name: SQUID_EXTRACTSERVICETIMES
              value: "{{ .Values.squidExporter.extractServiceTimes }}"
            {{- if .Values.squidExporter.squidLogin }}
            - name: SQUID_LOGIN
              value: "{{ .Values.squidExporter.squidLogin }}"
            {{- end }}
            {{- if .Values.squidExporter.squidPassword }}
            - name: SQUID_PASSWORD
              value: "{{ .Values.squidExporter.squidPassword }}"
            {{- end }}
          args:
            - -squid-hostname
            - "localhost"
            - -squid-port
            - "{{ .Values.service.port }}"
            - -listen
            - ":{{ .Values.squidExporter.port }}"
            - -metrics-path
            - "{{ .Values.squidExporter.metricsPath }}"
            {{- if .Values.squidExporter.squidLogin }}
            - -squid-login
            - "{{ .Values.squidExporter.squidLogin }}"
            {{- end }}
            {{- if .Values.squidExporter.squidPassword }}
            - -squid-password
            - "{{ .Values.squidExporter.squidPassword }}"
            {{- end }}
            {{- range $key, $value := .Values.squidExporter.customLabels }}
            - -label
            - "{{ $key }}={{ $value }}"
            {{- end }}
          livenessProbe:
            httpGet:
              path: {{ .Values.squidExporter.metricsPath }}
              port: metrics
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: {{ .Values.squidExporter.metricsPath }}
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.squidExporter.resources | nindent 12 }}
        {{- end }}
      volumes:
        - name: squid-config
          configMap:
            name: {{ include "squid.fullname" . }}-config
        # Mount the secret created by cert-manager
        - name: squid-certs-secret
          secret:
            secretName: {{ .Values.namespace.name }}-tls
        # A single volume for all of Squid's spool data, including the ssl_db
        # Use emptyDir instead of PVC
        - name: squid-spool-vol
          emptyDir: {}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
