apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "squid.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "squid.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "squid.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        # Trigger a redeployment when the configmap changes
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "squid.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "squid.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      # --- INIT CONTAINER ---
      # This container runs as root to prepare certificates, initialize the SSL DB,
      # and set the correct file permissions before the main Squid container starts.
      initContainers:
      - name: squid-init
        image: "{{ include "squid.image" . }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          # Must run as root to perform chown
          runAsUser: 0
        command:
          - /bin/sh
          - -c
          - |
            set -e
            echo "Preparing /var/spool/squid/ssl_db..."
            echo "Directory perms before setup:";
            ls -ld /var /var/spool /var/spool/squid
            mkdir -p /var/spool/squid
            chmod 0775 /var/spool/squid
            if [ ! -f /var/spool/squid/ssl_db/index.txt ]; then
              echo "(Re)creating SSL DB with security_file_certgen..."
              rm -rf /var/spool/squid/ssl_db
              /usr/lib64/squid/security_file_certgen -c -s /var/spool/squid/ssl_db -M 16MB
            else
              echo "SSL DB already initialized; skipping creation."
            fi

            echo "Ensuring squid log path and access.log exist..."
            mkdir -p /var/log/squid
            touch /var/log/squid/access.log
            chown -R {{ .Values.securityContext.runAsUser }}:{{ .Values.securityContext.runAsGroup }} /var/log/squid
            chmod -R g+rwX /var/log/squid

            echo "Setting permissions on /var/spool/squid for user {{ .Values.securityContext.runAsUser }}..."
            chown -R {{ .Values.securityContext.runAsUser }}:{{ .Values.securityContext.runAsGroup }} /var/spool/squid

            echo "Initialization complete."

        volumeMounts:
        # Mount the shared volume.
        - name: squid-spool-vol
          mountPath: /var/spool/squid
        # Mount shared logs volume
        - name: squid-logs
          mountPath: /var/log/squid

      containers:
        - name: squid
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ include "squid.image" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3128
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            tcpSocket:
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: squid-config
              mountPath: /etc/squid/squid.conf
              subPath: squid.conf
            # Shared logs volume so sidecar can read access logs
            - name: squid-logs
              mountPath: /var/log/squid
            - name: squid-certs-secret
              mountPath: /etc/squid/certs
              readOnly: true
            # Mount the entire spool directory for the main container
            - name: squid-spool-vol
              mountPath: /var/spool/squid
            {{- if .Values.test.enabled }}
            # Mount the test-server's CA bundle for upstream trust
            - name: test-server-ca-bundle-vol
              mountPath: /etc/squid/trust/test-server
              readOnly: true
            {{- end }}
        {{- if .Values.perSiteExporter.enabled }}
        - name: per-site-exporter
          image: "{{ include "squid.image" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: per-site-http
              containerPort: {{ .Values.perSiteExporter.port }}
              protocol: TCP
          command: ["/bin/sh","-c"]
          args:
           - tail -n +1 -F /var/log/squid/access.log | exec /usr/local/bin/squid-per-site-exporter -web.listen-address :{{ .Values.perSiteExporter.port }} -web.tls-cert-file /etc/squid/certs/tls.crt -web.tls-key-file /etc/squid/certs/tls.key
          livenessProbe:
            tcpSocket:
              port: per-site-http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: per-site-http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.perSiteExporter.resources | nindent 12 }}
          volumeMounts:
            - name: squid-logs
              mountPath: /var/log/squid
            - name: squid-certs-secret
              mountPath: /etc/squid/certs
              readOnly: true
        {{- end }}
        {{- if .Values.squidExporter.enabled }}
        - name: squid-exporter
          image: "{{ include "squid.image" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: {{ .Values.squidExporter.port }}
              protocol: TCP
          env:
            - name: SQUID_HOSTNAME
              value: "localhost"
            - name: SQUID_PORT
              value: "{{ .Values.service.port }}"
            - name: SQUID_EXPORTER_LISTEN
              value: ":{{ .Values.squidExporter.port }}"
            - name: SQUID_EXPORTER_METRICS_PATH
              value: "{{ .Values.squidExporter.metricsPath }}"
            - name: SQUID_EXTRACTSERVICETIMES
              value: "{{ .Values.squidExporter.extractServiceTimes }}"
            {{- if .Values.squidExporter.squidLogin }}
            - name: SQUID_LOGIN
              value: "{{ .Values.squidExporter.squidLogin }}"
            {{- end }}
            {{- if .Values.squidExporter.squidPassword }}
            - name: SQUID_PASSWORD
              value: "{{ .Values.squidExporter.squidPassword }}"
            {{- end }}
          args:
            - exporter
            - -squid-hostname
            - "localhost"
            - -squid-port
            - "{{ .Values.service.port }}"
            - -listen
            - ":{{ .Values.squidExporter.port }}"
            - -metrics-path
            - "{{ .Values.squidExporter.metricsPath }}"
            {{- if .Values.squidExporter.squidLogin }}
            - -squid-login
            - "{{ .Values.squidExporter.squidLogin }}"
            {{- end }}
            {{- if .Values.squidExporter.squidPassword }}
            - -squid-password
            - "{{ .Values.squidExporter.squidPassword }}"
            {{- end }}
            {{- range $key, $value := .Values.squidExporter.customLabels }}
            - -label
            - "{{ $key }}={{ $value }}"
            {{- end }}
          livenessProbe:
            httpGet:
              path: {{ .Values.squidExporter.metricsPath }}
              port: metrics
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: {{ .Values.squidExporter.metricsPath }}
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.squidExporter.resources | nindent 12 }}
        {{- end }}
      volumes:
        - name: squid-config
          configMap:
            name: {{ include "squid.fullname" . }}-config
        # Shared logs volume for per-site exporter sidecar
        - name: squid-logs
          emptyDir: {}
        # Mount the secret created by cert-manager
        - name: squid-certs-secret
          secret:
            secretName: {{ .Values.namespace.name }}-tls
        # A single volume for all of Squid's spool data, including the ssl_db
        # Use emptyDir instead of PVC
        - name: squid-spool-vol
          emptyDir: {}
        {{- if .Values.test.enabled }}
        # This volume makes the ConfigMap created by the test-server-bundle available
        - name: test-server-ca-bundle-vol
          configMap:
            name: test-server-bundle # This is the ConfigMap created by the Bundle in Step 5
            items:
            - key: ca.crt
              path: ca.crt          
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
