apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    name: {{ .Values.namespace.name }}
{{- if .Values.namespace.annotations }}
  annotations:
{{ toYaml .Values.namespace.annotations | indent 4 }}
{{- end }} 