{{- if (index .Values "selfsigned-bundle").enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.namespace.name }}-cert
  namespace: {{ .Values.namespace.name }}
spec:
  isCA: true
  subject:
    organizations:
      - konflux
  dnsNames:
  - localhost
  - {{ include "squid.fullname" . }}
  - {{ include "squid.fullname" . }}.{{ .Values.namespace.name }}.svc
  - {{ include "squid.fullname" . }}.{{ .Values.namespace.name }}.svc.cluster.local
  
  issuerRef:
    kind: ClusterIssuer
    name: {{ .Values.namespace.name }}-ca-issuer
  secretName: {{ .Values.namespace.name }}-tls
{{- end }}
