{{- if .Values.test.enabled }}
apiVersion: v1
kind: Pod
metadata:
  name: "{{ include "squid.fullname" . }}-test"
  namespace: {{ .Values.namespace.name }}
  labels:
    # Use different app name to avoid service selector conflicts
    app.kubernetes.io/name: squid
    app.kubernetes.io/instance: {{ include "squid.fullname" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: test
    app: {{ .Values.test.name }}
    helm.sh/chart: {{ include "squid.chart" . }}
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  restartPolicy: Never
  serviceAccountName: {{ include "squid.fullname" . }}-test
  containers:
  - name: ginkgo-test
    image: "{{ .Values.test.image.repository }}:{{ .Values.test.image.tag }}"
    imagePullPolicy: {{ .Values.test.image.pullPolicy | default "IfNotPresent" }}
    command:
    - /bin/bash
    - -c
    - |
      set -e
      echo "=== Starting Ginkgo E2E Tests ==="
      echo "Target namespace: {{ .Values.namespace.name }}"
      echo "Squid service: {{ include "squid.fullname" . }}.{{ .Values.namespace.name }}.svc.cluster.local:{{ .Values.service.port }}"
      
      # Run the compiled test binary
      echo "Running tests..."
      cd /app/tests
      ./e2e/e2e.test -ginkgo.v
    env:
    - name: SQUID_NAMESPACE
      value: "{{ .Values.namespace.name }}"
    - name: SQUID_SERVICE_NAME
      value: "{{ include "squid.fullname" . }}"
    - name: SQUID_SERVICE_PORT
      value: "{{ .Values.service.port }}"
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    resources:
      {{- toYaml .Values.test.resources | nindent 6 }}
{{- end }} 
 